# @package _global_
defaults:
  - /dataset: static_big
  - /training: local
  - /wandb: default
  - _self_

# Disable wandb for this computation
wandb:
  enabled: false

# Use CPU to avoid GPU allocation for simple MAC counting
training:
  params:
    cpu: true
    batch_size: 1
    num_workers: 0

# Group name for organization
group: macs-computation