# @package _global_
defaults:
  - /dataset: static_big         # Dataset selection
  - /training: default
  - /wandb: default
  - _self_

group: 0-baselines
model_artifact: none

wandb:
  tags: [evaluation]


hydra:
  mode: MULTIRUN
  sweeper:
    params:
      model_artifact: ghost-targets-offline_8.19K:latest, ghost-mix-offline_8.19K:latest, 
                      ghost-targets-streaming_8.19K:latest, ghost-mix-streaming_8.19K:latest

