# @package _global_
defaults:
  - /dataset: static_big         # Dataset selection
  - /training: default
  - /wandb: default
  - _self_

group: 0-baselines
model_artifact: none

wandb:
  tags: [evaluation]


hydra:
  mode: MULTIRUN
  sweeper:
    params:
      model_artifact: oracle-mix-streaming:latest, oracle-targets-offline:latest


num_runs: 1
