# @package _global_
defaults:
  - /dataset: static_big         # Dataset selection
  - /training: local
  - /wandb: default
  - _self_

group: eval-offline
model_artifact: none

wandb:
  tags: [evaluation]

hydra:
  mode: MULTIRUN
  sweeper:
    params:
      model_artifact: 
        S-mamba-streaming-sym-bidirect_1.10M:v0,
        L-mamba-streaming-sym-bidirect_19.74M:v0,
        S-mamba-streaming-asym-bidirect_1.10M:v0,
        S-mamba-streaming-short-asym-bidirect_1.10M:v0,
        S-conv-streaming-sym-bidirect_1.10M:v0,
        S-conv-streaming-asym-bidirect_1.10M:v0,
        S-transformer-streaming-sym-bidirect_1.08M:v0,
        S-transformer-streaming-asym-bidirect_1.08M:v0,
        L-transformer-streaming-sym-bidirect_19.84M:v0
        S-mamba-streaming-short-asym_1.10M:v0,
        S-mamba-streaming-asym_1.10M:v0,
        S-mamba-streaming-sym_1.10M:v0



training:
  params:
    batch_size: 10
    use_amp: false

ignore_confused: false
streaming_mode: true