# @package _global_
defaults:
  - /dataset: static_big         # Dataset selection
  - /training: default
  - /wandb: default
  - _self_

group: 1-offline
model_artifact: none

wandb:
  tags: [evaluation]


hydra:
  mode: MULTIRUN
  sweeper:
    params:
      model_artifact: m-transformer-offline_5.12M:latest

