# @package _global_
defaults:
  - _self_

publish_model: null

hydra:
  mode: MULTIRUN
  sweeper:
    params:
      publish_model: S-transformer-streaming-context_1.08M.pt, S-transformer-streaming-chunk_1.08M.pt, S-mamba-streaming-extended-chunk_1.10M.pt,
        S-mamba-streaming-chunk_1.10M.pt, S-liquid-streaming-chunk_1.04M.pt