# @package _global_
defaults:
  - wandb: default
  - _self_

publish_model: null

hydra:
  mode: MULTIRUN
  sweeper:
    params:
      publish_model: L-liquid-streaming-sym_20.11M.pt #,
#        S-conv-streaming-sym_1.10M.pt,
#        S-liquid-streaming-sym_1.04M.pt,
#        S-mamba-streaming-sym_1.10M.pt,
#        L-mamba-streaming-sym_19.74M.pt,
#        S-liquid-streaming-asym_1.04M.pt,
#        S-mamba-streaming-asym_1.10M.pt,
#        S-mamba-streaming-short-asym_1.10M.pt