# @package _global_
defaults:
  - _self_

publish_model: null

hydra:
  mode: MULTIRUN
  sweeper:
    params:
      publish_model: L-liquid-streaming-sym_20.11M,
        S-conv-streaming-sym_1.10M,
        S-liquid-streaming-sym_1.04M,
        S-mamba-streaming-sym_1.10M,
        L-mamba-streaming-sym_19.74M,
        S-liquid-streaming-asym_1.04M,
        S-mamba-streaming-asym_1.10M,
        S-mamba-streaming-short-asym_1.10M