# @package _global_
defaults:
  - _self_
  - optional /private: env
  - /runs/baselines: oracle_mix

hydra:
  mode: MULTIRUN
  sweeper:
    params:
      runs/baselines: oracle_mix,oracle_targets,oracle_mix_streaming,oracle_targets_streaming