# @package _global_
defaults:
  - /training: default
  - /wandb: default
  - _self_

group: 4-streaming

publish_model: null

hydra:
  mode: MULTIRUN
  sweeper:
    params:
      publish_model: M-transformer-streaming-asym-bidirect_5.11M.pt,
        M-mamba-streaming-asym-bidirect_5.11M.pt,
        S-liquid-streaming-asym-bidirect-2_1.04M.pt,
        S-mamba-streaming-asym-bidirect-2_1.10M.pt







