# @package _global_
defaults:
  - _self_
  - /runs/offline: m-tcn


hydra:
  mode: MULTIRUN
  sweeper:
    params:
      runs/streaming: l-conv-chunk, l-transformer-chunk, l-mamba-chunk, l-liquid-chunk, l-conv-context, 
        l-transformer-context, l-mamba-context, l-liquid-context, l-mamba-extended-chunk, m-transformer-context