# @package _global_
defaults:
  - _self_
  - /runs/streaming: l-mamba-chunk


hydra:
  mode: MULTIRUN
  sweeper:
    params:
      runs/streaming: l-mamba-chunk, l-liquid-chunk, l-transformer-chunk, l-transformer-context, l-mamba-context, 
        l-liquid-context, l-mamba-extended-chunk, l-conv-chunk, l-conv-context