# @package _global_
defaults:
  - _self_
  - /runs/streaming: s-mamba-chunk


hydra:
  mode: MULTIRUN
  sweeper:
    params:
      runs/streaming: s-mamba-chunk, s-liquid-chunk, s-transformer-chunk, s-transformer-context, s-mamba-context, 
        s-liquid-context, s-mamba-extended-chunk, s-conv-chunk, s-conv-context