# @package _global_
defaults:
  - /runs/streaming: s-transformer-sym
  - _self_

model_arch:
  encoder:
    causal: true
  decoder:
    causal: true
  separator:
    causal_proj: true

group: 4-streaming-causal

hydra:
  mode: MULTIRUN
  sweeper:
    params:
      runs/streaming: ghost_targets, s-mamba-sym, s-liquid-sym, s-transformer-sym, l-mamba-sym, l-liquid-sym, l-transformer-sym, 
        s-transformer-asym, s-mamba-asym, s-liquid-asym, s-mamba-short-asym, s-conv-sym, s-conv-asym