# @package _global_
defaults:
  - _self_
  - /runs/offline: m-tcn


hydra:
  mode: MULTIRUN
  sweeper:
    params:
      runs/offline: l-tcn, l-mamba, l-transformer, m-tcn, m-mamba, m-transformer, s-tcn, s-mamba, s-transformer