# @package _global_
defaults:
  - _self_
  - /runs/baselines: oracle_mix


hydra:
  mode: MULTIRUN
  sweeper:
    params:
      runs/baselines: ghost_targets  # ghost_targets, ghost_mix, ghost_targets_streaming, ghost_mix_streaming
