# @package _global_
defaults:
  - _self_
  - /runs/offline: m-tcn


hydra:
  mode: MULTIRUN
  sweeper:
    params:
      runs/offline: s-tcn, s-transformer, s-mamba, s-liquid

model_arch:
  use_spatial_features: false
