# @package _global_
defaults:
  - _self_
  - /runs/streaming: s-mamba-sym


hydra:
  mode: MULTIRUN
  sweeper:
    params:
      runs/streaming: ghost_targets, s-mamba-sym, s-liquid-sym, s-transformer-sym, l-mamba-sym, l-liquid-sym, l-transformer-sym, 
        s-transformer-asym, s-mamba-asym, s-liquid-asym, s-mamba-short-asym, s-conv-sym, s-conv-asym