# @package _global_
defaults:
  - /model_arch: identity          # Architecture selection
  - /dataset: static_small         # Dataset selection
  - /training: default
  - /wandb: default
  - /inference: default
  - _self_

name: ${model_arch.name}-targets-streaming
group: 0-baselines

# Adjustments
model_arch:
  use_spatial_features: false
  use_targets_as_input: true
  streaming_mode: true