# @package _global_
defaults:
  - /model_arch: tasnet            # Architecture selection
  - /dataset: static_big         # Dataset selection
  - /training: default
  - /wandb: default

  - override /model_arch/separator: mamba

name: M-${model_arch.name}-offline
group: 1-offline

# Adjustments
model_arch:
  use_spatial_features: true
  streaming_mode: false