# @package _global_
defaults:
  - /model_arch: tasnet            # Architecture selection
  - /dataset: static_big         # Dataset selection
  - /training: default
  - /wandb: default
  - _self_

name: m-${model_arch.name}-offline
group: 1-offline

# Adjustments
model_arch:
  use_spatial_features: true
  streaming_mode: true

training:
  params:
    batch_size: 50