# @package _global_
defaults:
  - m-mamba
  - _self_

name: XL-${model_arch.name}-offline

# Adjustments
model_arch:
  separator:
    scaler: 2.0
  feature_dim: 512


training:
  params:
    batch_size: 20