# @package _global_
defaults:
  - m-mamba
  - _self_

name: XL-${model_arch.name}-offline

# Adjustments
model_arch:
  separator:
    scaler: 5.0
    n_blocks: 8


training:
  params:
    batch_size: 20