_target_: "src.models.separator.TCNSeparator"
input_dim: ???
output_dim: ???
bn_dim:           256
hidden_dim:       512
num_layers:       8
num_stacks:       3
kernel_size:      3
skip_connection:  true
causal:           true
dilated:          true
