_target_: "src.models.separator.TCNSeparator"
input_dim: ???
output_dim: ???
bn_dim:           64
hidden_dim:       256
num_layers:       7
num_stacks:       5
kernel_size:      3
skip_connection:  true
causal:           true
dilated:          true
