# @package _global_
defaults:
  - s-transformer-sym
  - _self_

  - override /model_arch/separator: ghost

name: ${model_arch.name}-targets-offline-bidirect
group: 10-streaming-bidirect

# Adjustments
model_arch:
  streaming_mode: true
  no_separator: true
  use_spatial_features: false
  use_targets_as_input: true