# @package _global_
defaults:
  - l-transformer-chunk
  - _self_

  - override /model_arch/separator: mamba

# adjustments
name: $L-{model_arch.separator.name}-${model_arch.name}-streaming-extended-chunk

model_arch:
    context_size_ms: 6.0