# @package _global_
defaults:
  - s-transformer-sym
  - _self_

  - override /model_arch/separator: mamba

# adjustments
name: L-${model_arch.separator.name}-streaming-sym

model_arch:
  separator:
    scaler: 2.0

