# @package _global_
defaults:
  - l-transformer-chunk
  - _self_

# adjustments
name: L-${model_arch.separator.name}-${model_arch.name}-streaming-context

model_arch:
    separator:
      context_size_ms: 34.0