# @package _global_
defaults:
  - s-transformer-asym
  - _self_

# adjustments
name: L-${model_arch.separator.name}-streaming-asym-bidirect

model_arch:
    separator:
      scaler: 2.0
      context_size_ms: 34.0