# @package _global_
defaults:
  - /model_arch: tasnet            # Architecture selection
  - /dataset: static_small         # Dataset selection
  - /training: default
  - /wandb: default
  - /inference: default
  - _self_

  - override /model_arch/separator: transformer

name: $L-{model_arch.separator.name}-${model_arch.name}-streaming
group: 4-streaming

model_arch:
  streaming_mode: true
  encoder:
    causal: false
  decoder:
    causal: false
  separator:
    scaler: 2.0
    causal_proj: false