# @package _global_
defaults:
  - s-transformer-asym
  - _self_

  - override /model_arch/separator: tcn

# adjustments
name: S-${model_arch.separator.name}-streaming-asym

training:
    params:
        batch_size: 10