# @package _global_
defaults:
  - s-transformer-chunk
  - _self_

  - override /model_arch/separator: liquid

# adjustments
name: S-${model_arch.separator.name}-streaming-chunk

training:
    params:
        batch_size: 70