# @package _global_
defaults:
  - s-transformer-context
  - _self_

  - override /model_arch/separator: liquid

# adjustments
name: S-${model_arch.name}-streaming-context

training:
    params:
        batch_size: 70