# @package _global_
defaults:
  - s-transformer-asym
  - _self_

  - override /model_arch/separator: mamba

# adjustments
name: S-${model_arch.separator.name}-streaming-short-asym

model_arch:
  separator:
    context_size_ms: 6.0