# @package _global_
defaults:
  - s-transformer-chunk
  - _self_

  - override /model_arch/separator: mamba

# adjustments
name: S-${model_arch.separator.name}-streaming-extended-chunk

model_arch:
  separator:
    context_size_ms: 6.0

training:
    params:
      batch_size: 70