# @package _global_
defaults:
  - /model_arch: tasnet            # Architecture selection
  - /dataset: static_big         # Dataset selection
  - /training: default
  - /wandb: default
  - _self_

  - override /model_arch/separator: transformer

name: S-${model_arch.name}-streaming-sym
group: 4-streaming

model_arch:
  streaming_mode: true
  encoder:
    causal: false
  decoder:
    causal: false
  separator:
    scaler: 0.45
    causal_proj: false
    context_size_ms: ${model_arch.stream_chunk_size_ms}

training:
  params:
    batch_size: 70
    max_epochs: 40