# @package _global_
defaults:
  - /dataset: static_big
  - /training: default
  - /wandb: default
  - _self_

model_artifact: none


inference:
  input_audio_file: "test\\mixture\\mix_clip_000847_clip_002307.wav"
  output_audio_file: "mix_clip_000847_clip_002307.wav"
  output_dir: "outputs/inference"
  save_to_wandb: false

wandb:
  enabled: true
  tags: [inference]

hydra:
  mode: MULTIRUN
  sweeper:
    params:
      model_artifact:
        S-mamba-streaming-sym-bidirect_1.10M:v0,
        L-mamba-streaming-sym-bidirect_19.74M:v0,
        S-mamba-streaming-asym-bidirect_1.10M:v0,
        S-mamba-streaming-short-asym-bidirect_1.10M:v0,
        S-mamba-streaming-short-asym_1.10M:v0,



training:
  params:
    batch_size: 1
    use_amp: false
    num_workers: 10

streaming_mode: true 