_target_: "src.models.separator.LiquidSeparator"
name: "Liquid"

context_size_ms: ${model_arch.stream_chunk_size_ms} # length of the data the separator process at each forward pass
num_neurons: 40
time_first: true
