_target_: src.models.separator.MambaSeparator
name: "mamba"

context_len_ms: ${model_arch.window_length_ms}  # length of the streaming buffer for the model
d_model: ${model_arch.feature_dim}       # Input and output dimension (must match encoder output dim)
d_state: 64                              # State size for Mamba SSM
d_conv: 4                                # Local conv width | Should maybe match TCN = 4.0 ms = 64 samples @ 16 kHz
expand: 2                                # Expansion factor inside Mamba
