_target_: "src.models.separator.MambaSeparator"
name: "mamba"

streaming_mode: ${model_arch.streaming_mode}
context_size_ms: ${model_arch.stream_chunk_size_ms}

input_dim: 64
output_dim: 2   # e.g., 2xD mask for 2 speakers

# Model dimensions
scaler: 1.0  # Scaling factor for model dimensions
expand: 2
headdim: ${mul:${model_arch.separator.scaler} , 68}  # Dimension of each attention head
d_model: ${mul:${model_arch.separator.headdim}, ${mul:${model_arch.separator.expand}, 2}  # Internal model dimension
d_ff: ${mul:${model_arch.separator.d_model}, 4}             # Feed-forward dimension
n_blocks: 5

dropout_val: 0.1
d_state: 16
d_conv: 4
causal_proj: true

frames_per_output: 64
