defaults:
  - model_arch: tasnet
  - dataset: static
  - training: default
  - wandb: default
  - inference: default
  - override model_arch/separator: liquid

name: ${model_arch.separator.name}-${model_arch.name}
