encoder:
  _target_: "src.models.tasnet.VanillaEncoder"
  N: 64            # number of basis filters in encoder
  L: 64            # filter length (samples; 4 ms @16 kHz)
  stride: 32       # hop size (samples; usually L//2)
  causal: true     # whether to use causal convolution

#separator:
#  _target_: "src.models.tasnet.VanillaDecoder"
#  num_stacks: 5        # number of repeated TCN stacks
#  blocks_per_stack: 7  # convolutional blocks per stack

decoder:
  _target_: "src.models.tasnet.VanillaDecoder"
  N: 64            # number of basis filters in decoder
  L: 64            # filter length (samples; 4 ms @16 kHz)
  stride: 32       # hop size (samples; usually L//2)
  causal: true     # whether to use causal convolution

feature_dim: 512   # STFT window length (samples; 32 ms @16 kHz)
stft_stride: 32    # STFT hop length (samples; 2 ms @16 kHz)