train:
  mixture: "../datasets/static/train/mixture"
  clean: "../datasets/static/train/clean"

val:
  mixture: "../datasets/static/val/mixture"
  clean: "../datasets/static/val/clean"

test:
    mixture: "../datasets/static/test/mixture"
    clean: "../datasets/static/test/clean"
