# @package _global_
defaults:
  - /model_arch: tasnet          # Architecture selection
  - /dataset: static_big         # Dataset selection
  - /training: default
  - /wandb: default
  - _self_

  - override /model_arch/separator: ghost

name: ${name}-mix-offline
group: 0-baselines

# Adjustments
model_arch:
  no_separator: true
  use_spatial_features: false
  use_targets_as_input: false
  streaming_mode: false