# @package _global_
defaults:
  - /model_arch: oracle          # Architecture selection
  - /dataset: static_big         # Dataset selection
  - /training: default
  - /wandb: default
  - _self_

name: ${model_arch.name}-mix-offline
group: 0-baselines

# Adjustments
model_arch:
  use_spatial_features: false
  use_targets_as_input: false
  streaming_mode: false