defaults:
  - _self_
  - model_arch: tasnet            # Architecture selection
  - dataset: static_big         # Dataset selection
  - training: default
  - wandb: default
  - inference: default

name: ${model_arch.separator.name}-${model_arch.name}-offline
group: tests