defaults:
  - model_arch: tasnet      # Architecture selection
  - dataset: static         # Dataset selection
  - training: default

  - override model_arch/separator: mamba

name: ${model_arch.separator.name}${model_arch.name}