# @package hydra.launcher
defaults:
  - submitit_slurm
  - _self_

partition: GPUQ
account: share-ie-idi
nodes: 1
gres: gpu:1
constraint: "h100|a100&gpu80g"
mem_gb: 20
timeout_min: 3000  # 50 hours



