# @package hydra.launcher
defaults:
  - submitit_slurm   # << inherits all submitit_* keys
  - _self_                           # … then let THIS file override fields

partition: GPUQ
account: share-ie-idi
nodes: 1
gres: gpu:1
#constraint: "v100|a100"
mem_gb: 32
timeout_min: 120 # 2 hours
