_wandb:
    value:
        cli_version: 0.19.11
        m: []
        python_version: 3.13.0
        t:
            "1":
                - 1
                - 50
                - 55
            "2":
                - 1
                - 50
                - 55
            "3":
                - 13
                - 23
                - 55
            "4": 3.13.0
            "5": 0.19.11
            "8":
                - 2
                - 5
            "10":
                - 20
            "12": 0.19.11
            "13": darwin-arm64
