_target_: "src.models.encoder.TasNetEncoder"
num_filters: 64      # number of basis filters
filter_length: 64    # filter length in samples (4 ms @16 kHz)
stride: 32           # hop size (L//2) !must be equal to stft_hop_size!
causal: true         # causal convolution