# @package _global_
defaults:
  - /dataset: static_big
  - /training: default
  - /wandb: default
  - _self_

training:
  params:
    batch_size: 1
    num_workers: 1

# Group name for organization
group: efficiency